image:
  - Visual Studio 2017
environment:
  nodejs_version: "8"
  matrix:
  - PYTHON: "C:\\Python33-x64"
    DISTUTILS_USE_SDK: "1"
  - PYTHON: "C:\\Python34-x64"
    DISTUTILS_USE_SDK: "1"
  - PYTHON: "C:\\Python35-x64"
  - PYTHON: "C:\\Python36-x64"
cache:
  - node_modules 
  - bower_components
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install typescript -g
configuration: Release
before_test:
  - tsc
  - tsc -v
  - node --version
  - npm --version
test_script:
  - npm test
after_build:
  - npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
build: off