image:
    - Visual Studio 2017
environment:
    nodejs_version: "10.4.0"
    matrix:
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
platform: x64
cache:
    - node_modules
install: 
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "%PYTHON%/Scripts/pip3.exe install -r requirements.txt nose"
    - ps: Install-Product node $env:nodejs_version
    - node --version
    - npm --version
    - npm install
    - npm install typescript -g
configuration: Release
before_test:
    - cmd: "%PYTHON%\\python --version"
    - cmd: "%PYTHON%/Scripts/pip3.exe --version"
    - cmd: "%PYTHON%/Scripts/pip3.exe list"
    - tsc
    - tsc -v
    - node --version
    - npm --version
test_script:
    - npm test
after_build:
    - npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
build: off